route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 4h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: ''
        chat_id: 
        api_url: 'https://api.telegram.org'
        parse_mode: 'HTML'
        disable_notifications: false